env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard-with-typescript
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
rules: {}
settings:
  import/resolver:
    typescript: []
ignorePatterns: ["vite.config.ts", "vite-env.d.ts"]
